# Generated by Django 5.1.4 on 2025-01-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tff5BulletEmails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_message_id', models.CharField(max_length=255, unique=True)),
                ('email_date', models.DateTimeField()),
                ('email_title', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tff_5bullet_emails',
                'managed': False,
                'verbose_name': 'TFF 5Bullet Email',
                'verbose_name_plural': 'TFF 5Bullet Emails',
            },
        ),
        migrations.CreateModel(
            name='TffBullets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bullet_heading', models.CharField(max_length=255)),
                ('bullet_content', models.TextField()),
                ('searchable_bullet_content', models.TextField()),
            ],
            options={
                'db_table': 'tff_bullets',
                'managed': False,
                'verbose_name': 'TFF Bullet',
                'verbose_name_plural': 'TFF Bullets',
            },
        ),
    ]
